import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const fontStyle = Nunito({
	weight: ['200', '400', '800', '1000'],
	subsets: ['latin']
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={fontStyle.className}>{children}</body>
		</html>
	);
}
